vich_uploader:
    db_driver: orm

    mappings:
        model_bp_files:
           uri_prefix: '%model_bp_files%'
           upload_destination: '%kernel.project_dir%/public%model_bp_files%'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           delete_on_update: true
           delete_on_remove: true
        model_vb_files:
           uri_prefix: '%model_vb_files%'
           upload_destination: '%kernel.project_dir%/public%model_vb_files%'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           delete_on_update: true
           delete_on_remove: true
