monolog:
    channels: ['db']
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event"]
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type: firephp
        #    level: info
        #chromephp:
        #    type: chromephp
        #    level: info

        # part from logger see log.php/dBProcessor.php/DbHandler.php/DoctrineSubcriber.php/monolog.yaml/service.yaml
        # console:
        #     type: console
        #     process_psr_3_messages: false
        #     channels: ["!event", "!doctrine", "!console"]
        # dbHandler:
        #     type: service
        #     id: monolog.dbHandler
        #     channels: ['db']
            
